{{- if and .Values.ingress.enabled .Values.ingress.basicAuth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "llama-cpp.fullname" . }}-basic-auth
  labels:
    {{- include "llama-cpp.labels" . | nindent 4 }}
spec:
  basicAuth:
    {{- if .Values.ingress.basicAuth.existingSecret }}
    secret: {{ .Values.ingress.basicAuth.existingSecret }}
    {{- else if gt (len .Values.ingress.basicAuth.users) 0 }}
    secret: {{ include "llama-cpp.fullname" . }}-basic-auth
    {{- end }}
{{- end }}
