{{- if and .Values.ingress.enabled .Values.ingress.basicAuth.enabled (not .Values.ingress.basicAuth.existingSecret) (gt (len .Values.ingress.basicAuth.users) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turingpi-llama-cpp.fullname" . }}-basic-auth
  labels:
    {{- include "turingpi-llama-cpp.labels" . | nindent 4 }}
type: Opaque
stringData:
  users: |-
    {{- range .Values.ingress.basicAuth.users }}
    {{ . }}
    {{- end }}
{{- end }}
